####Possíveis requisições para tipo (Não é permitido deletar um tipo de usuário)
POST http://localhost:3030/tipo
Content-Type: application/json

{
    "descricao":"Administrador"
}

#############

GET http://localhost:3030/tipo/2
Content-Type: application/json

#############

PUT http://localhost:3030/tipo
Content-Type: application/json

{
    "id":1,
    "descricao":"Usuário"
}

###########################



####Possíveis requisições para endereço (Não é permitido deletar um endereço)
POST http://localhost:3030/endereco
Content-Type: application/json

{
"cep":"02341-123",
"logadouro":"Rua das felicidades, 1",
"complemento":"Apartamento 1",
"estado" :"São Paulo",
"cidade":"São Paulo",
}

# /*
# "id_locadora":1
# "id_usuario":1
# Incluir FK somente da entidade a qual pertence o endereço*/   
#############

GET http://localhost:3030/endereco/1
Content-Type: application/json

#############

PUT http://localhost:3030/endereco
Content-Type: application/json

{
    "id":1,
"cep":"02341-153",
"logadouro":"Rua das Superações, 1",
"complemento":"Apartamento 1",
"estado" :"São Paulo",
"cidade":"São Paulo"  
}

###########################



####Possíveis requisições para mensagem (Não é permitido alterar uma mensagem)
POST http://localhost:3030/mensagem
Content-Type: application/json

{
"nome_completo":"Carinha que mora logo ali",
"email":"sucodefruta@badstyle.com",
"conteudo":"Hey, me passa um dolar!"
}

#############

GET http://localhost:3030/mensagem/1
Content-Type: application/json

#############

GET http://localhost:3030/mensagem
Content-Type: application/json

#############
DELETE  http://localhost:3030/mensagem
Content-Type: application/json

{
"id":1
}
###########################

####Possíveis requisições para Status de veículo (Não é permitido deletar um tipo de status)
POST http://localhost:3030/status
Content-Type: application/json

{
    "descricao":"Alugado"
}

#############

GET http://localhost:3030/status/1
Content-Type: application/json

#############

GET http://localhost:3030/status/
Content-Type: application/json

#############
PUT http://localhost:3030/status
Content-Type: application/json

{
    "id":1,
    "descricao":"Disponível"
}

###########################



####Possíveis requisições para Locadora
POST http://localhost:3030/locadora
Content-Type: application/json

{
"nome":"Ag. 01 - SP",
"email":"ag01sp@locar.com",
"cnpj":"00000000000000",
"telefone" :"21 55322342"
}

#############

GET http://localhost:3030/locadora/1
Content-Type: application/json

#############

GET http://localhost:3030/locadora
Content-Type: application/json

#############

PUT http://localhost:3030/locadora
Content-Type: application/json

{
    "id":1,


}

###########################

DELETE  http://localhost:3030/locadora
Content-Type: application/json

{
    "id":1
}
##############################


####Possíveis requisições para Reserva
POST http://localhost:3030/reserva
Content-Type: application/json

{
    "id_veiculo": 1,
    "fk_id_usuario": 1,
    "fk_id_locadora_retirada":1,
    "fk_id_locadora_entrega": 2,
    "data_retirada":  "2022-03-28T23:08:13.145Z",
    "data_entrega": "2022-04-29T23:08:13.145Z",
    "valor": 3200.21
}

#############


GET http://localhost:3030/reserva/usuario/1
Content-Type: application/json

#############


GET http://localhost:3030/reserva/1
Content-Type: application/json

#############

GET http://localhost:3030/reserva
Content-Type: application/json

#############

PUT http://localhost:3030/locadora
Content-Type: application/json

{
    "id":1,
"nome":"Ag. 01 - SP",
"email":"ag01sp@locar.com",
"cnpj":"00.000.000/0000-00",
"telefone" :"11 55882342"
}

###########################














